'use client'
import { useState } from 'react'
import { BarChart3, Bell, ChevronDown, CreditCard, LayoutDashboard, Menu, Plus, Settings, Tags, TrendingDown, TrendingUp, Wallet, X } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import './styles.css'

type Tab = 'Overview' | 'Expenses' | 'Incomes' | 'Loans' | 'Categories'
const tabs: Tab[] = ['Overview','Expenses','Incomes','Loans','Categories']
const chart = [{month:'Jan',amount:2100},{month:'Feb',amount:1650},{month:'Mar',amount:2400},{month:'Apr',amount:1950},{month:'May',amount:2800},{month:'Jun',amount:1396}]
const transactions = [{name:'Groceries',category:'Food & Dining',amount:128.4,date:'Today'},{name:'Monthly rent',category:'Housing',amount:1200,date:'Jun 01, 2026'},{name:'Uber rides',category:'Transport',amount:48.25,date:'May 30, 2026'},{name:'Netflix subscription',category:'Entertainment',amount:19.99,date:'May 28, 2026'}]
const icons = {Overview:LayoutDashboard,Expenses:TrendingDown,Incomes:TrendingUp,Loans:CreditCard,Categories:Tags}

export default function Home(){
 const [tab,setTab]=useState<Tab>('Overview'); const [menu,setMenu]=useState(false); const [add,setAdd]=useState(false)
 return <div className="app-shell">
  <aside className={menu?'sidebar open':'sidebar'}><div className="brand"><div className="brand-mark">$</div><div><strong>Ledgerly</strong><span>Personal finance</span></div><button className="close-mobile" onClick={()=>setMenu(false)}><X/></button></div><nav>{tabs.map(item=>{const Icon=icons[item];return <button key={item} className={tab===item?'nav-item active':'nav-item'} onClick={()=>{setTab(item);setMenu(false)}}><Icon/>{item}</button>})}</nav><div className="sidebar-bottom"><button className="nav-item"><Settings/>Settings</button><div className="user-card"><div className="avatar">JD</div><div><strong>Jordan Davis</strong><span>jordan@email.com</span></div></div></div></aside>
  {menu&&<div className="scrim" onClick={()=>setMenu(false)}/>}<main className="main"><header><button className="menu" onClick={()=>setMenu(true)}><Menu/></button><div><p className="eyebrow">Tuesday, June 16, 2026</p><h1>{tab==='Overview'?'Good morning, Jordan.':tab}</h1></div><button className="icon-btn"><Bell/><i/></button></header>
  {tab==='Overview'?<Overview onAdd={()=>setAdd(true)} onView={()=>setTab('Expenses')}/>:<Module tab={tab} onAdd={()=>setAdd(true)}/>}</main>
  {add&&<div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><p className="eyebrow">New record</p><h2>Add transaction</h2></div><button className="icon-btn" onClick={()=>setAdd(false)}><X/></button></div><label>Description<input placeholder="e.g. Coffee with client"/></label><div className="two-col"><label>Amount<input type="number" placeholder="0.00"/></label><label>Date<input type="date" defaultValue="2026-06-16"/></label></div><label>Category<select><option>Food & Dining</option><option>Housing</option><option>Transport</option></select></label><div className="modal-actions"><button className="secondary" onClick={()=>setAdd(false)}>Cancel</button><button className="primary" onClick={()=>setAdd(false)}>Save transaction</button></div></div></div>}
 </div>
}
function Overview({onAdd,onView}:{onAdd:()=>void,onView:()=>void}){return <><section className="hero-row"><div><p className="eyebrow">Your financial overview</p><h2>Stay on top of your money.</h2><p className="muted">Here&apos;s how your finances are looking this month.</p></div><button className="primary" onClick={onAdd}><Plus/>Add transaction</button></section><section className="stat-grid"><Stat label="Total balance" value="$12,680.42" change="+8.4%" tone="purple" icon={<Wallet/>}/><Stat label="Monthly income" value="$8,420.00" change="+12.2%" tone="green" icon={<TrendingUp/>}/><Stat label="Monthly expenses" value="$3,496.64" change="-4.8%" tone="orange" icon={<TrendingDown/>}/><Stat label="Savings rate" value="58.5%" change="+6.1%" tone="blue" icon={<BarChart3/>}/></section><section className="content-grid"><div className="card chart-card"><div className="card-head"><div><h3>Expense overview</h3><p className="muted">Your spending over the last six months</p></div><button className="select">Last 6 months <ChevronDown/></button></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart}><CartesianGrid vertical={false} stroke="#e8e9ef"/><XAxis dataKey="month" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false} tickFormatter={v=>`$${v/1000}k`}/><Tooltip/><Bar dataKey="amount" fill="#6c63ff" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></div><div className="card category-card"><h3>Spending by category</h3><p className="muted">This month</p><div className="category-summary"><strong>$1,932</strong><span>spent across 4 categories</span></div>{['Housing','$1,200','#f59e0b','Food & Dining','$428','#6c63ff','Transport','$218','#10b981','Entertainment','$86','#ec4899'].reduce((a,v,i,arr)=>i%3===0?[...a,<div className="legend-row" key={String(v)}><span className="dot" style={{background:arr[i+2] as string}}/>{v}<strong>{arr[i+1]}</strong></div>]:a,[] as React.ReactNode[])}</div></section><section className="card table-card"><div className="card-head"><div><h3>Recent transactions</h3><p className="muted">Your latest activity</p></div><button className="link-button" onClick={onView}>View all →</button></div><table><thead><tr><th>TRANSACTION</th><th>CATEGORY</th><th>DATE</th><th>AMOUNT</th></tr></thead><tbody>{transactions.map(t=><tr key={t.name}><td><span className="transaction-icon">{t.name[0]}</span><strong>{t.name}</strong></td><td>{t.category}</td><td className="muted">{t.date}</td><td className="amount negative">− ${t.amount.toFixed(2)}</td></tr>)}</tbody></table></section></>}
function Stat({label,value,change,tone,icon}:{label:string,value:string,change:string,tone:string,icon:React.ReactNode}){return <div className="stat card"><div className={'stat-icon '+tone}>{icon}</div><p className="muted">{label}</p><strong className="stat-value">{value}</strong><span className={change.startsWith('-')?'change down':'change'}>{change} <small>vs last month</small></span></div>}
function Module({tab,onAdd}:{tab:Tab,onAdd:()=>void}){return <div className="module"><div className="hero-row"><div><p className="eyebrow">Manage your money</p><h2>{tab}</h2><p className="muted">Keep your records organized and up to date.</p></div><button className="primary" onClick={onAdd}><Plus/>Add record</button></div><div className="card empty-module"><div className="empty-icon"><Tags/></div><h3>Your {tab.toLowerCase()} will appear here</h3><p className="muted">Connect MongoDB Atlas to load and manage your real data.</p><button className="secondary" onClick={onAdd}>Create your first record</button></div></div>}
